// this is for loader only
export const SET_LOADER_STATES = "SET_LOADER_STATES";


// For Auth 
//for signout 
export const SIGN_OUT = "SIGN_OUT";

export const AUTH_CLEARE_STATE = "AUTH_CLEARE_STATE";

// For Login
export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS";
export const LOG_IN_FAIL = "LOG_IN_FAIL";


// For Admin 
// for cleare states of admin reducer
export const ADMIN_CLEARE_STATE = "ADMIN_CLEARE_STATE";

// for GET_SYSTEM_SUPPORTED_LANGUAGE Api
export const GET_SYSTEM_SUPPORTED_LANGUAGE_SUCCESS = "GET_SYSTEM_SUPPORTED_LANGUAGE_SUCCESS";
export const GET_SYSTEM_SUPPORTED_LANGUAGE_FAIL = "GET_SYSTEM_SUPPORTED_LANGUAGE_FAIL";

// for GET_LAST_SELECTED_LANGUAGE Api
export const GET_LAST_SELECTED_LANGUAGE_SUCCESS = "GET_LAST_SELECTED_LANGUAGE_SUCCESS";
export const GET_LAST_SELECTED_LANGUAGE_FAIL = "GET_LAST_SELECTED_LANGUAGE_FAIL";

// for SET_LAST_SELECTED_LANGUAGE Api
export const SET_LAST_SELECTED_LANGUAGE_SUCCESS = "SET_LAST_SELECTED_LANGUAGE_SUCCESS";
export const SET_LAST_SELECTED_LANGUAGE_FAIL = "SET_LAST_SELECTED_LANGUAGE_FAIL";
