// this is for loader only
export const SET_LOADER_STATES = "SET_LOADER_STATES";

// For Auth
//for signout
export const SIGN_OUT = "SIGN_OUT";

export const AUTH_CLEARE_STATE = "AUTH_CLEARE_STATE";

// For Login
export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS";
export const LOG_IN_FAIL = "LOG_IN_FAIL";

// For Admin
// for cleare states of admin reducer
export const ADMIN_CLEARE_STATE = "ADMIN_CLEARE_STATE";

// for GET_SYSTEM_SUPPORTED_LANGUAGE Api
export const GET_SYSTEM_SUPPORTED_LANGUAGE_SUCCESS =
  "GET_SYSTEM_SUPPORTED_LANGUAGE_SUCCESS";
export const GET_SYSTEM_SUPPORTED_LANGUAGE_FAIL =
  "GET_SYSTEM_SUPPORTED_LANGUAGE_FAIL";

// for GET_LAST_SELECTED_LANGUAGE Api
export const GET_LAST_SELECTED_LANGUAGE_SUCCESS =
  "GET_LAST_SELECTED_LANGUAGE_SUCCESS";
export const GET_LAST_SELECTED_LANGUAGE_FAIL =
  "GET_LAST_SELECTED_LANGUAGE_FAIL";

// for SET_LAST_SELECTED_LANGUAGE Api
export const SET_LAST_SELECTED_LANGUAGE_SUCCESS =
  "SET_LAST_SELECTED_LANGUAGE_SUCCESS";
export const SET_LAST_SELECTED_LANGUAGE_FAIL =
  "SET_LAST_SELECTED_LANGUAGE_FAIL";

//for All Shifts Of Branch Api fot(Branch Admin for listing of all branches && Branch Roaster for Shifts drop down)
export const GET_ALL_SHIFTS_OF_BRANCH_SUCCESS =
  "GET_ALL_SHIFTS_OF_BRANCH_SUCCESS";
export const GET_ALL_SHIFTS_OF_BRANCH_FAIL = "GET_ALL_SHIFTS_OF_BRANCH_FAIL";

//for ALL COUNTERS OF BRANCH Api fot(CounterMain for listing of all branches && Branch Roaster for Counter drop down)
export const ALL_COUNTERS_OF_BRANCH_SUCCESS = "ALL_COUNTERS_OF_BRANCH_SUCCESS";
export const ALL_COUNTERS_OF_BRANCH_FAIL = "ALL_COUNTERS_OF_BRANCH_FAIL";

//for Branch Admin for adding new shift
export const ADD_BRANCH_SHIFT_SUCCESS = "ADD_BRANCH_SHIFT_SUCCESS";
export const ADD_BRANCH_SHIFT_FAIL = "ADD_BRANCH_SHIFT_FAIL";

export const ROASTER_CLEARING_STATE = "ROASTER_CLEARING_STATE";

export const ADD_BRANCH_ROASTER_ENTRY_SUCCESS =
  "ADD_BRANCH_ROASTER_ENTRY_SUCCESS";
export const ADD_BRANCH_ROASTER_ENTRY_FAILED =
  "ADD_BRANCH_ROASTER_ENTRY_FAILED";

export const GET_SINGLE_DAY_BRANCH_ROASTER_SUCCESS =
  "GET_SINGLE_DAY_BRANCH_ROASTER_SUCCESS";

export const GET_SINGLE_DAY_BRANCH_ROASTER_FAILED =
  "GET_SINGLE_DAY_BRANCH_ROASTER_FAILED";

export const REMOVE_BRANCH_ROASTER_ENTRY_SUCCESS =
  "REMOVE_BRANCH_ROASTER_ENTRY_SUCCESS";

export const REMOVE_BRANCH_ROASTER_ENTRY_FAILED =
  "REMOVE_BRANCH_ROASTER_ENTRY_FAILED";
